(install
 (section share)
 (package marmoset)
 (files
  (marmoset/result.go as runtime/go/marmoset/result.go)
   (marmoset/option.go as runtime/go/marmoset/option.go)
   (marmoset/unit.go as runtime/go/marmoset/unit.go)
   (marmoset/bytes.go as runtime/go/marmoset/bytes.go)
   (marmoset/handle.go as runtime/go/marmoset/handle.go)
   (shims/test/scalar/scalar.go as runtime/go/shims/test/scalar/scalar.go)
   (shims/test/other/other.go as runtime/go/shims/test/other/other.go)
   (shims/test/result/result.go as runtime/go/shims/test/result/result.go)
   (shims/test/status/status.go as runtime/go/shims/test/status/status.go)
   (shims/test/type/type.go as runtime/go/shims/test/type/type.go)))
