(install
 (section share)
 (package marmoset)
 (files
  (marmoset/result.go as runtime/go/marmoset/result.go)
  (marmoset/option.go as runtime/go/marmoset/option.go)
  (marmoset/unit.go as runtime/go/marmoset/unit.go)
  (marmoset/bytes.go as runtime/go/marmoset/bytes.go)
  (marmoset/handle.go as runtime/go/marmoset/handle.go)
  (marmoset/helpers.go as runtime/go/marmoset/helpers.go)
  (shims/std/basics/basics.go as runtime/go/shims/std/basics/basics.go)
  (shims/std/bytes/bytes.go as runtime/go/shims/std/bytes/bytes.go)
  (shims/std/file/file.go as runtime/go/shims/std/file/file.go)))
