(install
 (section share)
 (package marmoset)
 (files
  (prelude.mr as std/prelude.mr)
  (basics.mr as std/basics.mr)
  (option.mr as std/option.mr)
  (result.mr as std/result.mr)
  (error.mr as std/error.mr)
  (bytes.mr as std/bytes.mr)
  (path.mr as std/path.mr)
  (file.mr as std/file.mr)
  (dir.mr as std/dir.mr)
  (io.mr as std/io.mr)
  (io/err.mr as std/io/err.mr)))
