name: Cross Platform Matrix (Manual)

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "master"

jobs:
  integration-cross-platform:
    name: Integration (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - windows-latest

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5

      - name: Set-up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"

      - run: opam install . --deps-only --with-test

      - run: opam exec -- ./test/integration.sh
