name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Roc
        uses: hasnep/setup-roc@main
        with:
          roc-version: nightly

      - name: Run unit tests
        run: make unit
